npm install

#echo Running SimpleDecoderEncoder
#node SimpleDecoderEncoder

echo Running SimpleVideoDecoderBuffer
node SimpleVideoDecoderBuffer

echo Running SimpleVideoDecoderRender
node SimpleVideoDecoderRender

echo Running SimpleVideoDecoderRenderBuffer
node SimpleVideoDecoderRenderBuffer

echo Running SimpleVideoDecoderRenderTunnel
node SimpleVideoDecoderRenderTunnel