npm install

echo Running CameraEffects
node CameraEffects

echo Running CameraPipe
node CameraPipe

echo Running CameraTunnel
node CameraTunnel

echo Running SimpleVideoDecoderBuffer
node SimpleVideoDecoderBuffer

echo Running SimpleVideoDecoderRender
node SimpleVideoDecoderRender

echo Running SimpleVideoDecoderRenderBuffer
node SimpleVideoDecoderRenderBuffer

echo Running SimpleVideoDecoderRenderTunnel
node SimpleVideoDecoderRenderTunnel